### PR TITLE
Add missing variable definition needed for search on Sphinx 3

### PR DESCRIPTION
**Pull request by mdickinson**
Search is currently broken with Sphinx 3: the search results lead to an invalid URL containing an "undefined" string. 

xref: enthought/traits#1046.
xref: enthought/traits#1048

This PR fixes that.

Before this goes in, I'll check for other definitions that are present with the upstream theme but not here.

### CODE REVIEW

**Comment by mdickinson** [comment]
I also need to double check that this still works with the latest Sphinx 2.x version from the buildsystem.

**Comment by mdickinson** [comment]
@corranwebster Could you test for the TraitsUI and Pyface documentation? This is working for Traits. If it's also working for TraitsUI and Pyface, I'll make a quick release of enthought-sphinx-theme.

**Comment by mdickinson** [comment]
> I'll check for other definitions that are present with the upstream theme but not here.

Done. I added `SOURCELINK_SUFFIX`.

> I also need to double check that this still works with the latest Sphinx 2.x version from the buildsystem.

Also done.

**Comment by mdickinson** [comment]
@corranwebster I think this is good to go. In local testing, I no longer see any JS console warnings or errors when using the search functionality for Traits, and I see search result content that I've never seen before:

Screenshot 2020-04-28 at 13 16 21

**Comment by mdickinson** [comment]
@ievacerny @kitchoi If either of you has bandwidth for a review of the form "I tested this PR with <insert random ETS project here> and Sphinx version <some_version> and it <worked / almost worked / failed horribly / exploded / delete as applicable>", that would be welcome too.

**Comment by mdickinson** [comment]
@kitchoi Thanks! Merging and releasing.

**Comment by kitchoi** [comment]
I forgot to go back to Sphinx 2 to check if the theme also works. So I just did that, and it works fine. :)

**Comment by mdickinson** [comment]
Thank you!

**Pull request merged**
