### PR TITLE
New Enthought Branding

### PR DESCRIPTION
**Pull request by corranwebster**
This is a first attempt at applying the new Enthought branding to the existing template.  Major changes are:

- switch Source Sans Pro font to Poppins
- adjust colors to new Enthought brand colors
- use new logo

Needs OK from various Enthought stakeholders before merging.

Overall look is this:
image

### CODE REVIEW

**Comment by corranwebster** [comment]
Not sure what's causing the bumpiness in the navigation bubbles.

**Comment by corranwebster** [comment]
Fixed the misalignment of the nav bars.

Enthought's marketing says that this is good to go.

**Review by jwiggins — COMMENTED** [review]
The logo went from 300x300 to 800x800, but I don't see any CSS to control its size. What happens when you use this on a large screen?

**Comment by jwiggins** [comment]
Answer: It's pretty giant
<details>
Screen Shot 2022-03-03 at 10 17 16
</details>

**Review by jwiggins — APPROVED** [review]
The logo needs some guardrails, but otherwise LGTM

**Comment by corranwebster** [comment]
Ended up rescaling to 200x200 as that looked better when expanding.

**Comment by jwiggins** [comment]
Yup. That looks better.

**Comment by corranwebster** [comment]
Thanks for the review

**Pull request merged**
